### ISSUE TITLE
About the training data in your paper.

### ISSUE THREAD

**Issue by LeeWlving** [ldz666666/Style-atk#3]
Thank you for your excellent job. In readme you mentioned your gan generated images, can your share the data? Thank you!

**Comment by DongzeLi-CASIA** [comment]
Sorry, the dataset for training the forensic models cannot be shared, but you can collect the synthesized data using [StyleGAN](https://github.com/NVlabs/stylegan2), the real data is from [FFHQ](https://github.com/NVlabs/ffhq-dataset). Fake dataset also includes faces generated from [Faceshifter](https://github.com/maum-ai/faceshifter) and [MegaFS](https://github.com/zyainfal/One-Shot-Face-Swapping-on-Megapixels).
